#!/usr/bin/env bash

dir="$(realpath -m .)"
pattern=""

for ((i=1; i<="${#}"; i++))
do
	if [ "${i}" == "-dd" ]
	then
		i=$((i+1))
		dir="${i}"
	else
		pattern="${pattern}(?=.*${!i})"
	fi
done

cmd="find \"${dir}\" | grep -P \"${pattern}\" | sed -E 's|(.*)|\"\1\"|g'"
eval "${cmd}"
