#!/usr/bin/env bash
this_path="$(readlink --canonicalize-missing "${BASH_SOURCE[0]}")"
date_dir_name=`date +%F_%T`
config_dir="$HOME/.$(basename "${this_path}")"
date_dir="${config_dir}/${date_dir_name}"

cmd="mkdir \"${date_dir}\" -p"
#echo "${cmd}"
eval "${cmd}"

for i in "${@}"; do
	cmd="mv -t \"${date_dir}\" \"${i}\""
	#echo "${cmd}"
	eval "${cmd}"
done
