#!/usr/bin/env bash

this_file="$(readlink --canonicalize-missing "${BASH_SOURCE[0]}")"
this_file_name="$(basename "${this_file}")"
this_dir="$(dirname "${this_file}")"


if [ "${1}" == "bash" ]; then
	if [ "${2}" != "" ]; then
		mkdir "${2}"/src/main -p;
		mkdir "${2}"/src/test -p;
		touch "${2}"/README.org
	else
		echo "project name is empty"
	fi
else
	cat "${this_file}"
	echo "${this_file}"
fi
